name: ces-mma
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.11.3
  - spyder-kernels
  - pip
  - pylint
  - black
  - numpy
  - matplotlib
  - tqdm
  - scipy
  - pyserial
  - pandas
  - pip:
    - telemetrix